# OSEMN Exercises

In [1]:
%matplotlib inline
import pandas as pd
import numpy as np

1\. Create a random list of number and then save it to a text file named "simple_data.txt"

In [2]:
import random
randomlist = random.sample(range(0, 100), 5)
print(randomlist)

[31, 88, 94, 40, 11]


In [3]:
with open("simple_data.txt", "w") as output:
    output.write(str(randomlist))

In [23]:
with open("simple_data.txt", mode='r') as f:
    for line in f:
        for c in line.split(): print(c)

[31,
88,
94,
40,
11]


2\. Create a random matrix of 5x5 and then save it to a text file named "data.txt"

In [8]:
random_matrix = np.random.randint(100, size=(5, 5))
print(random_matrix)

[[15 12 20 52 31]
 [28 43 36  3 19]
 [93 97 69 11 54]
 [69 32 45 31 84]
 [81 65 35 32 92]]


In [9]:
with open("data.txt", "w") as output:
    output.write(str(random_matrix))

3\. Load the saved txt file of point 2 and convert it to a csv file (by hand)

In [57]:
import csv

with open('data.txt', 'r') as in_file:
    stripped = (line.strip() for line in in_file)
    lines = (line.split(",") for line in stripped if line)
    with open('csv_matrix.csv', 'w') as out_file:
        writer = csv.writer(out_file)
        writer.writerows(lines)

4\. load the binary file named *credit_card.dat* and convert the data into the real credit-card number.
Each line correspond to a credit card number.
Each character is composed by 6 bit (even the space) and the last 4 bit are just a padding

**hint**: use the `chr()` function to convert a number to a char

In [1]:
with  open('credit_card.dat','rb') as file:
    file_content=file.read()
    number_counter=0
    number_size = 6 # size of the word in bytes
    for line in file_content:
        for i in range(0, len(line), number_size):
            int(line[0+number_size*i:number_size+number_size*i])

TypeError: object of type 'int' has no len()

In [ ]:
    for i in range(0, len(file_content), word_size):
        word_counter+=1

In [77]:
number_size=6
line='1001010011101010'
len(line)

16

In [89]:
number_size=6
line='110111110110'
for i in range(0, len(line), number_size):
    k=int(line[i:number_size+i],2)
    print(chr(k))

7
6


5\. Load the file "user_data.json", filter the data by the "CreditCardType" field equals to "American Express". Than save the data a to CSV.

6\. Load the file from this url: [https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1](https://www.dropbox.com/s/7u3lm737ogbqsg8/mushrooms_categorized.csv?dl=1) with Pandas. 
+ Explore the data (see the info of the data)
+ Draw the istogram of the 'class' field. Decribe wath yuou see


7\. Load the remote file [https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1](https://www.dropbox.com/s/vkl89yce7xjdq4n/regression_generated.csv?dl=1) with Pandas and plot a scatter plot all possible combination of the following fields:
    
  + features_1
  + features_2
  + features_3

8\. Load the same file of point 6, and convert the file to json with Pandas.